### ISSUE TITLE
FocusLost event sometimes does not fire when pane with vim inside is zooming

### ISSUE THREAD

**Issue by hoango7604** [TaDaa/vimade#58]
I recently install this plugin in order to trigger FocusLost event and fade vim inside inactive tmux pane using [TaDaa/vimade](https://github.com/TaDaa/vimade). Everything works fine, except for when vim is inside tmux pane which is being zoom and then I switch to another pane, sometimes it fades and sometimes doesn't.

__Details:__
- OS: MacOS
- vim version: 8.2.
- tmux version: 3.1c
- terminal: iTerm2

__My vim config__: [config repository](https://github.com/hoango7604/vim-config)

__Expected behavior__: Vim immediately fades after switched from it's containing tmux pane to another pane.
__Actual behavior__: Sometimes Vim fades and sometimes it doesn't.

__Attachment:__
![issue-attachment-gif](https://media.giphy.com/media/QniwFbur9t5vTnY2rE/giphy.gif)

**Comment by TaDaa** [comment]
interesting behavior -- After a few tests it seems like the following is happening:

- Switching panes with Ctrl-B+ArrowDirection , works fine / instantly
- Creating a new pane with Ctrl-b-" or Ctrl-b-% causes a delay before the FocusLost event is fired.  The delay required seems to be consistent with updatetime.  The caveat seems to be that if updatetime triggers before the newly bottom created pane finishes loading, FocusLost never fires (I'm guessing because CursorHold does not retrigger at this point).
- Things get a bit stranger by swapping usecursorhold=0 (which causes vimade to use timer mechanisms instead).  FocusLost now fires in conjunction with the timer.

In the short term, I think that ensuring ```let g:vimade.usecursorhold=0``` would give you a better behavior.  I'll have to dig into vim-tmux-focus-events later and see if anything stands out.
